name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: PSScriptAnalyzer check
        run: .\PSScriptAnalyzer-Check.ps1
        shell: powershell
